############################################################
# Production config overrides
#
# Use with: JEKYLL_ENV=production bundle exec jekyll build \
#             --config _config.yml,_config.production.yml
############################################################

# Production Sass output should be compressed
sass:
  style: compressed
